default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: pong_development
test:
  <<: *default
  database: pong_test
production:
  <<: *default
  database: pong_production
